/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the authenticated household profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                id: string;
                version: number;
                /** @enum {string} */
                status: 'active' | 'suspended' | 'closed';
                residentId: string;
                name: string;
                firstName: string;
                timezone: string;
                consentVersion: string;
                /** Format: date-time */
                consentedAt: string;
                /** Format: date-time */
                createdAt: string;
              };
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Update the resident profile */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @constant */
            action: 'update';
            expectedVersion: number;
            name: string;
            firstName: string;
            timezone: string;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/notification-preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read own email preference without exposing contact addresses */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                id: string;
                version: number;
                enabled: boolean;
                /** @enum {string} */
                suppression: 'none' | 'bounce' | 'complaint' | 'removed';
              };
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Update own email consent preference */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @constant */
            action: 'update';
            expectedVersion: number;
            enabled: boolean;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read current active membership and permissions */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                subject: string;
                role: string;
                circleMemberId?: string;
                permissions: string[];
              };
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/home': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get calm home overview */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                resident: unknown;
                oneThing: unknown;
                calendar: unknown[];
                devices: components['schemas']['HomeDevice'][];
              };
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Perform a versioned simulated home-device action */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            action: string;
            entityId?: string;
            expectedVersion?: number;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get One Thing task session */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: unknown;
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Manage task session */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            action: string;
            entityId?: string;
            expectedVersion?: number;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/access': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get access preferences */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['AccessSettings'];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Update access preferences */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @constant */
            action: 'update';
            entityId?: string;
            expectedVersion?: number;
            preferences: components['schemas']['AccessPreferences'];
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/circle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get scoped Circle availability */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['CircleMember'][];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Manage Circle membership or availability */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            action: string;
            entityId?: string;
            expectedVersion?: number;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/safety-windows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Safety Windows */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['SafetyWindow'][];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Create or transition a Safety Window */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json':
            | {
                /** @constant */
                action: 'create';
                title: string;
                template: components['schemas']['SafetyWindowTemplate'];
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                expectedBy: string;
                graceMinutes: number;
                escalationMemberIds: string[];
              }
            | {
                /** @enum {string} */
                action: 'check-in' | 'close-early' | 'cancel' | 'record-missed-check';
                entityId: string;
                expectedVersion: number;
              };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/help-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List help requests */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['HelpRequest'][];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Create or respond to a help request */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            action: string;
            entityId?: string;
            expectedVersion?: number;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/incidents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List independent incident aggregates */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Incident'][];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Coordinate an incident */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            action: string;
            entityId?: string;
            expectedVersion?: number;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/playbooks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List house playbooks */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Playbook'][];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Create or advance a playbook run */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json':
            | {
                /** @constant */
                action: 'create';
                title: string;
                steps: string[];
              }
            | {
                /** @enum {string} */
                action: 'next-step' | 'start' | 'pause' | 'resume' | 'cancel' | 'reset';
                entityId: string;
                expectedVersion: number;
              };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/privacy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get privacy controls */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['PrivacySettings'];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Update privacy or request a scoped confirmation */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            action: 'update' | 'request-confirmation';
            entityId?: string;
            expectedVersion?: number;
            /** @enum {string} */
            confirmationPurpose?:
              | 'change-escalation-plan'
              | 'disclose-access-instructions'
              | 'share-location'
              | 'remove-primary-contact'
              | 'destructive-privacy-change';
            confirmationToken?: string;
            routineSharing?: boolean;
            /** @enum {string} */
            locationSharing?: 'off' | 'incident-only' | 'always';
            temporaryPrivateUntil?: string | null;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Short-lived scoped confirmation prepared */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              confirmation: components['schemas']['ConfirmationToken'];
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/house-memory': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get authorized House Memory */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['HouseMemoryItem'][];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** Manage House Memory */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Unique command key retained for duplicate suppression. */
          'Idempotency-Key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            action: 'add' | 'update';
            entityId?: string;
            expectedVersion?: number;
            label: string;
            value: string;
            /** @enum {string} */
            category: 'home' | 'routine' | 'maintenance' | 'contact';
            /** @enum {string} */
            sensitivity: 'routine' | 'sensitive' | 'incident-only';
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandResult'];
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get privacy-preserving product metrics */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: {
                [key: string]: number;
              };
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/intent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Interpret a redacted resident utterance without executing it */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['MinimalIntentContext'];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              intent: components['schemas']['InterpretedIntent'];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description The optional Bedrock interpreter is unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/demo/intent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Interpret a synthetic demo utterance without executing it */
    post: {
      parameters: {
        query?: never;
        header: {
          'X-STAY-Demo-Session': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['MinimalIntentContext'];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              intent: components['schemas']['InterpretedIntent'];
              provenance: {
                /** @enum {string} */
                mode: 'live' | 'simulated' | 'unavailable';
                provider: string;
                /** Format: date-time */
                observedAt: string;
                reason?: string;
              };
            };
          };
        };
        /** @description Invalid or missing command metadata */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Permission denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description Optimistic concurrency or state conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description The optional Bedrock interpreter is unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/demo-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a per-browser isolated demo session */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description TTL-scoped session */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DemoSession'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccessPreferences: {
      /** @enum {string} */
      interactionMode: 'voice-first' | 'touch-first' | 'balanced';
      reducedLoad: boolean;
      highLegibility: boolean;
      captions: boolean;
      extraResponseTime: boolean;
      repeatInformation: boolean;
      highContrast: boolean;
      reducedMotion: boolean;
      /** @enum {string} */
      textScale: 'default' | 'large' | 'extra-large';
    };
    /** @enum {string} */
    SafetyWindowTemplate:
      'morning-check-in' | 'arrived-home' | 'medication-routine' | 'meal-check' | 'custom';
    MinimalIntentContext: {
      utterance: string;
      /** @enum {string} */
      currentSurface:
        | 'home'
        | 'tasks'
        | 'access'
        | 'windows'
        | 'circle'
        | 'incidents'
        | 'playbooks'
        | 'privacy'
        | 'memory';
      visibleEntityIds: string[];
      locale: string;
    };
    ApiError: {
      /** @enum {string} */
      code:
        | 'BAD_REQUEST'
        | 'UNAUTHENTICATED'
        | 'FORBIDDEN'
        | 'NOT_FOUND'
        | 'CONFLICT'
        | 'STALE_VERSION'
        | 'IDEMPOTENCY_REQUIRED'
        | 'CONFIRMATION_REQUIRED'
        | 'PROVIDER_UNAVAILABLE'
        | 'INTERNAL_ERROR';
      message: string;
      fieldDetails?: {
        [key: string]: string[];
      };
      correlationId: string;
    };
    CommandResult: {
      entity: unknown;
      version: number;
      emittedEvents: {
        id: string;
        type: string;
        aggregateType: string;
        aggregateId: string;
        householdId: string;
        /** Format: date-time */
        occurredAt: string;
        actorSubject: string;
        data: {
          [key: string]: unknown;
        };
      }[];
      confirmationRequired: string | null;
      provenance: {
        /** @enum {string} */
        mode: 'live' | 'simulated' | 'unavailable';
        provider: string;
        /** Format: date-time */
        observedAt: string;
        reason?: string;
      };
    };
    HomeDevice: {
      id: string;
      name: string;
      /** @enum {string} */
      kind: 'path-light' | 'entry-sensor' | 'utility-sensor';
      /** @enum {string} */
      state: 'on' | 'off' | 'ready' | 'closed' | 'normal' | 'unavailable';
      version: number;
      /** Format: date-time */
      updatedAt: string;
      provenance: {
        /** @enum {string} */
        mode: 'live' | 'simulated' | 'unavailable';
        provider: string;
        /** Format: date-time */
        observedAt: string;
        reason?: string;
      };
    };
    AccessSettings: {
      /** @enum {string} */
      interactionMode: 'voice-first' | 'touch-first' | 'balanced';
      reducedLoad: boolean;
      highLegibility: boolean;
      captions: boolean;
      extraResponseTime: boolean;
      repeatInformation: boolean;
      highContrast: boolean;
      reducedMotion: boolean;
      /** @enum {string} */
      textScale: 'default' | 'large' | 'extra-large';
      id: string;
      version: number;
    };
    CircleMember: {
      id: string;
      version: number;
      active: boolean;
      name: string;
      initials: string;
      /** @enum {string} */
      role: 'resident' | 'coordinator' | 'nearby-helper' | 'backup' | 'aide';
      priority: number;
      /** @enum {string} */
      availability: 'available' | 'busy' | 'unavailable' | 'responding';
      responseMinutes: number;
      permissions: (
        | 'home:read'
        | 'home:act'
        | 'tasks:write'
        | 'circle:read'
        | 'circle:manage'
        | 'safety-window:read'
        | 'safety-window:manage'
        | 'help:request'
        | 'help:respond'
        | 'incident:read'
        | 'incident:coordinate'
        | 'incident:resolve'
        | 'access:manage'
        | 'privacy:manage'
        | 'memory:read'
        | 'memory:manage'
        | 'playbook:execute'
      )[];
      relationship: string;
    };
    SafetyWindow: {
      id: string;
      residentId: string;
      residentName: string;
      title: string;
      /** @enum {string} */
      template:
        'morning-check-in' | 'arrived-home' | 'medication-routine' | 'meal-check' | 'custom';
      /** @enum {string} */
      state:
        | 'scheduled'
        | 'open'
        | 'checked-in'
        | 'first-check-missed'
        | 'grace'
        | 'escalating'
        | 'cancelled'
        | 'resolved';
      /** Format: date-time */
      startsAt: string;
      /** Format: date-time */
      expectedBy: string;
      graceMinutes: number;
      checkAttempts: number;
      escalationMemberIds: string[];
      version: number;
      timeline: {
        id: string;
        /** Format: date-time */
        at: string;
        kind: string;
        title: string;
        detail: string;
        actorName: string;
      }[];
    };
    HelpRequest: {
      id: string;
      residentId: string;
      title: string;
      detail: string;
      /** @enum {string} */
      urgency: 'normal' | 'time-sensitive' | 'urgent';
      /** @enum {string} */
      state: 'open' | 'offered' | 'assigned' | 'declined' | 'completed' | 'cancelled';
      offeredTo: string[];
      assignedTo?: string;
      /** Format: date-time */
      createdAt: string;
      version: number;
      timeline: {
        id: string;
        /** Format: date-time */
        at: string;
        kind: string;
        title: string;
        detail: string;
        actorName: string;
      }[];
    };
    Incident: {
      id: string;
      residentId: string;
      /** @enum {string} */
      kind:
        | 'missed-window'
        | 'power-outage'
        | 'water-leak'
        | 'extreme-heat'
        | 'severe-weather'
        | 'custom';
      title: string;
      /** @enum {string} */
      state:
        | 'detected'
        | 'verifying'
        | 'active'
        | 'coordinating'
        | 'responding'
        | 'escalated'
        | 'resolved';
      /** @enum {string} */
      severity: 'watch' | 'attention' | 'urgent';
      assignedMemberId?: string;
      accessInstructionsAvailable: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      resolvedAt?: string;
      version: number;
      timeline: {
        id: string;
        /** Format: date-time */
        at: string;
        kind: string;
        title: string;
        detail: string;
        actorName: string;
      }[];
    };
    Playbook: {
      id: string;
      title: string;
      /** @enum {string} */
      kind: 'power-outage' | 'water-leak' | 'extreme-heat' | 'severe-weather' | 'custom';
      /** @enum {string} */
      state: 'ready' | 'running' | 'paused' | 'completed' | 'cancelled';
      steps: {
        id: string;
        label: string;
        completed: boolean;
      }[];
      provenance: {
        /** @enum {string} */
        mode: 'live' | 'simulated' | 'unavailable';
        provider: string;
        /** Format: date-time */
        observedAt: string;
        reason?: string;
      };
      version: number;
    };
    PrivacySettings: {
      id: string;
      version: number;
      routineSharing: boolean;
      /** @enum {string} */
      locationSharing: 'off' | 'incident-only' | 'always';
      /** Format: date-time */
      temporaryPrivateUntil?: string;
      /** @constant */
      auditRetention: true;
    };
    ConfirmationToken: {
      token: string;
      /** @enum {string} */
      purpose:
        | 'change-escalation-plan'
        | 'disclose-access-instructions'
        | 'share-location'
        | 'remove-primary-contact'
        | 'destructive-privacy-change';
      subject: string;
      entityId: string;
      /** Format: date-time */
      expiresAt: string;
      /** Format: date-time */
      consumedAt?: string;
    };
    HouseMemoryItem: {
      id: string;
      label: string;
      value: string;
      /** @enum {string} */
      category: 'home' | 'routine' | 'maintenance' | 'contact';
      /** @enum {string} */
      sensitivity: 'routine' | 'sensitive' | 'incident-only';
      /** Format: date-time */
      updatedAt: string;
      version: number;
    };
    InterpretedIntent: {
      /** @enum {string} */
      toolName:
        | 'get_home_overview'
        | 'manage_task_session'
        | 'manage_safety_window'
        | 'request_help'
        | 'get_circle_availability'
        | 'manage_incident'
        | 'manage_house_memory'
        | 'execute_playbook'
        | 'manage_privacy'
        | 'perform_home_action';
      action: string;
      entityId?: string;
      explanation: string;
      explicitEmergencyLanguage: boolean;
    };
    DemoSession: {
      id: string;
      browserKeyHash: string;
      householdId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      expiresAt: string;
      /** @constant */
      mode: 'isolated-demo';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
